name: 'Setup padne'
description: 'Install system dependencies, KiCad, and padne itself'
runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-full python3-dev python3-pip git libegl1 libegl1-mesa-dev libmpfr-dev libgmp-dev libboost-dev

    - name: Add KiCad PPA and install KiCad
      shell: bash
      run: |
        sudo add-apt-repository --yes ppa:kicad/kicad-9.0-releases
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends kicad

    - name: Install pygerber from git
      shell: bash
      run: |
        pip3 install --break-system-packages --user git+https://github.com/Argmaster/pygerber

    - name: Build C++ part of the repository, install the package
      shell: bash
      run: |
        pip3 install --break-system-packages --user -e .[test] -v
