name: Build Binary

on:
  workflow_call: # Allow this workflow to be called by other workflows
    inputs:
      retention_days:
        type: number
        default: 30
        description: "Artifact retention period in days"
    outputs:
      artifact_name:
        description: "Name of the uploaded binary artifact"
        value: ${{ jobs.build.outputs.artifact_name }}

permissions:
  contents: read

jobs:
  build:
    name: "Build PyInstaller Binary"
    runs-on: ubuntu-24.04
    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.name }}
    steps:
      - name: Set artifact name
        id: set_artifact_name
        run: |
          echo "name=padne-linux-x64-${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Padne dependencies
        uses: ./.github/actions/setup-padne

      - name: Install PyInstaller
        run: |
          pip3 install --break-system-packages --user pyinstaller

      - name: Create binary with PyInstaller
        run: |
          pyinstaller --clean --noconfirm padne.spec

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.name }}
          path: dist/padne
          retention-days: ${{ inputs.retention_days }}
