name: Run Tests

on: [push, pull_request]
permissions:
  checks: write
  contents: read

jobs:
  build_and_test:
    name: "Run Tests"
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Setup Padne
      uses: ./.github/actions/setup-padne

    - name: Run tests with pytest and generate report
      run: |
        python3 -m pytest --junitxml=pytest-results.xml

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always() # Always run this step to publish results, even if tests fail
      with:
        name: Pytest Results
        path: pytest-results.xml
        reporter: java-junit
        fail-on-error: 'true'
