name: Run Benchmarks

on: [push, pull_request]
permissions:
  contents: read

jobs:
  benchmark_suite:
    name: "Run Benchmark Suite"
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Padne
      uses: ./.github/actions/setup-padne

    - name: Install ASV benchmark framework
      run: |
        pip3 install --break-system-packages --user -e .[bench] -v
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure ASV machine (non-interactive)
      run: |
        asv machine --yes --machine ci-runner

    - name: Run benchmarks (quick mode, no results saved)
      run: |
        asv run HEAD^! --quick --dry-run --show-stderr
